### ISSUE TITLE
add Japanese strings for all modules

### ISSUE THREAD

**Issue by willbur1984** [BionBilateral/BBFrameworks#19]
- [x] MediaPlayer.strings
- [x] Validation.strings
- [x] MediaPicker.strings
- [x] AddressBook.strings
- [x] WebKit.strings
- [x] Foundation.strings
- [x] Keychain.strings

**Comment by willbur1984** [comment]
@jasonranderson When you get a chance, can you look over these? I stubbed out everything using Google translate.

**Comment by jasonranderson** [comment]
[b14543af037056](https://github.com/BionBilateral/BBFrameworks/commit/b14543af037056a2104bc24b64d5eaf7b3793a10) - oops. Forgot to mention the issue in my commit message.
